# Generated by Django 4.1.4 on 2022-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_newsletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
