# Generated by Django 4.1.4 on 2022-12-10 13:49

from django.db import migrations, models
import newsletters.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[newsletters.validators.validate_phone_number]),
        ),
    ]
