# Generated by Django 4.1.4 on 2022-12-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_alter_message_client_alter_message_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_active',
        ),
    ]
