# Generated by Django 4.1.4 on 2022-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_remove_client_is_active_remove_message_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
